spring:
  datasource:
    url: jdbc:postgresql://dpg-cvmttpgdl3ps73d7pq3g-a.oregon-postgres.render.com/duck_service_database_unsu
    username: ${database_username}
    password: ${database_password}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always