name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write  # Added permission for creating check runs

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated version

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: List test reports
        run: ls target/surefire-reports/  # Verify the test reports exist

      - name: Report
        uses: dorny/test-reporter@v1  # Updated version
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Build and push the Docker image
        run: |
          echo "Logging into Docker Hub..."
          docker login --username dgbhanderi --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
          echo "Building Docker image..."
          docker build -t ghcr.io/hbahramian/ducks-service:latest --file Dockerfile .
          echo "Pushing Docker image..."
          docker push ghcr.io/hbahramian/ducks-service:latest
